zuul:
  routes:
    users:
      path: /test/**
      #write here the route of the called application
      url: http://example.com/rest-service/greeting


logging:
  level:
    org:
      springframework:
        cloud:
          netflix: trace
